/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.33.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  commission_rate: number;
}
export type ExecuteMsg = {
  create_listing: {
    description: string;
    image_url: string;
    price: Uint128;
    title: string;
    token_denom: string;
  };
} | {
  update_listing: {
    description?: string | null;
    image_url?: string | null;
    listing_id: number;
    price?: Uint128 | null;
    title?: string | null;
  };
} | {
  cancel_listing: {
    listing_id: number;
  };
} | {
  buy_item: {
    listing_id: number;
  };
} | {
  update_config: {
    commission_rate?: number | null;
  };
};
export type Uint128 = string;
export type QueryMsg = {
  get_config: {};
} | {
  get_listing: {
    listing_id: number;
  };
} | {
  get_listings: {
    limit?: number | null;
    start_after?: number | null;
    status?: ListingStatus | null;
  };
} | {
  get_user_listings: {
    limit?: number | null;
    seller: string;
    start_after?: number | null;
  };
};
export type ListingStatus = "active" | "sold" | "cancelled";
export interface ConfigResponse {
  commission_rate: number;
  listing_count: number;
  owner: string;
}
export type Addr = string;
export interface ListingResponse {
  listing: Listing;
}
export interface Listing {
  created_at: number;
  description: string;
  id: number;
  image_url: string;
  price: Uint128;
  seller: Addr;
  status: ListingStatus;
  title: string;
  token_denom: string;
  updated_at?: number | null;
}
export interface ListingsResponse {
  listings: Listing[];
}
export interface UserListingsResponse {
  listings: Listing[];
}