/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.33.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CowrieMarketplace.types";
import * as _1 from "./CowrieMarketplace.client";
import * as _2 from "./CowrieMarketplace.message-composer";
import * as _3 from "./CowrieMarketplace.react-query";
export namespace contracts {
  export const CowrieMarketplace = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
}